[project]
name = "build-mkdocs"
version = "0.0.1"
description = "Build mkdocs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "mkdocs-with-confluence>=0.2.9",
    "pathspec>=1.0.3",
    "pyyaml>=6.0.3",
]
